### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by TKX42** [aazuspan/Voithos#6]
I am working on a similar project (https://github.com/Tristi-X/F.R.I.D.A.Y), which uses Wit.ai for the AI natural language processing. Today I found your project and I really like your CommandHandler, which is much better than my method. I just wanted to ask if it's ok, if I'm inspire my Code a bit only from your CommandHandler.py and your structure of command scripts?
So maybe, if you wanna check out my project, too, we could maybe bring the best of each together, I don't know..

**Comment by aazuspan** [comment]
Feel free to borrow from this as much as you like! I got busy with other projects and have abandoned this for now, but if I ever come back to it I'll be sure to check out your project and maybe implement some of your ideas. Good luck!
